# Generated by Django 3.1.6 on 2021-04-02 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Service', models.CharField(choices=[('Threading', 'Threading'), ('Facial', 'Facial'), ('Manicure Pedicure', 'Manicure Pedicure'), ('Hair Cut', 'Hair Cut'), ('Hair Colour', 'Hair Colour'), ('Makeup', 'Makeup')], max_length=30, null=True)),
                ('AppointDate', models.DateField(null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Desc', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
