# Generated by Django 3.1.6 on 2021-04-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210404_1939'),
        ('Saloon', '0002_auto_20210404_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment2',
            name='AppointDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment2',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
