# Generated by Django 3.1.6 on 2021-04-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Services2',
        ),
    ]
