# Generated by Django 3.1.6 on 2021-04-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210402_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services2',
        ),
    ]
